# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    doctrine.orm.naming_strategy.underscore_number_aware:
        class: Doctrine\ORM\Mapping\UnderscoreNamingStrategy
        arguments: [false, true]
    Psr\Log\LoggerInterface: '@monolog.logger'
