name: CI – tests & coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Si votre projet est VRAIMENT en Node :
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          npm install                         # ← remplace npm ci
          npm test -- --coverage --coverageReporters=cobertura

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/cobertura-coverage.xml
